---
# tasks file for apigee-opdk-yum-repository/

- name: Configure Yum repositories
  yum_repository:
     enabled: "{{ yum_repositories_enabled }}"
     state: present
     name: "{{ item.repo_id }}"
     description: "{{ item.name }}"
     baseurl: "{{ item.baseurl }}"
     file: '{{ item.yum_repo_filename }}'
  with_items: "{{ yum_repositories }}"
  when: yum_repositories is defined
